#this yaml file creates network and keypair 
---
- hosts: localhost
  tasks:
  - name: Create new keypair from current user's default SSH key
    os_keypair:
      state: present
      name: "{{ lookup('file', './temp/ansible_key') }}"
      public_key_file: ./temp/publickey
  - name: Create the test network
    os_network:
      state: present
      name: "{{ lookup('file', './temp/network') }}"
      external: False
      shared: False
    register: testnet_network
  - local_action: copy content={{ testnet_network.id }} dest=./temp/testnetwork.id

  - name: Create the test subnet
    os_subnet:
      state: present
      network_name: "{{ testnet_network.id }}"
      name: "{{ lookup('file', './temp/subnet') }}"
      ip_version: 4
      cidr: 192.168.0.0/24
      gateway_ip: 192.168.0.1
      enable_dhcp: yes
      dns_nameservers:
        - 8.8.8.8
    register: testnet_sub
  - local_action: copy content={{ testnet_sub.id }} dest=./temp/testnetsub.id

  - name: Create the test router
    ignore_errors: yes #for some reasons, re-running this task gives errors
    os_router:
      state: present
      name: "{{ lookup('file', './temp/router') }}"
      network: ext-net
      interfaces:
        - "{{ lookup('file', './temp/subnet') }}"
    register: testnet_router
  - local_action: copy content={{ testnet_router }} dest=./temp/testnetrouter
